// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACQqLJjk0x52oAd0go2GEL2Gh1YQ6_ztI',
    appId: '1:142496500450:web:aaa6a30867ee773b31ecbb',
    messagingSenderId: '142496500450',
    projectId: 'events-f1ff2',
    authDomain: 'events-f1ff2.firebaseapp.com',
    storageBucket: 'events-f1ff2.firebasestorage.app',
    measurementId: 'G-HDZKG411Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6CJFesMUuPKENkdTjC8DDiwr8lcP-qFg',
    appId: '1:142496500450:android:9221a9de5d6751ec31ecbb',
    messagingSenderId: '142496500450',
    projectId: 'events-f1ff2',
    storageBucket: 'events-f1ff2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXBuZDBbovcKdJiTax0_-n_4QNK48u7Eo',
    appId: '1:142496500450:ios:68202ccdc215aa9831ecbb',
    messagingSenderId: '142496500450',
    projectId: 'events-f1ff2',
    storageBucket: 'events-f1ff2.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXBuZDBbovcKdJiTax0_-n_4QNK48u7Eo',
    appId: '1:142496500450:ios:68202ccdc215aa9831ecbb',
    messagingSenderId: '142496500450',
    projectId: 'events-f1ff2',
    storageBucket: 'events-f1ff2.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACQqLJjk0x52oAd0go2GEL2Gh1YQ6_ztI',
    appId: '1:142496500450:web:d0c0a6a68230bda531ecbb',
    messagingSenderId: '142496500450',
    projectId: 'events-f1ff2',
    authDomain: 'events-f1ff2.firebaseapp.com',
    storageBucket: 'events-f1ff2.firebasestorage.app',
    measurementId: 'G-CSG8NMQZCH',
  );
}
